// line 1 "TableLayoutParser.rl"
// Do not edit this file! Generated by Ragel.

package com.esotericsoftware.tablelayout;

import java.util.ArrayList;

class TableLayoutParser {
	static public void parse (BaseTableLayout table, String input) {
		char[] data = (input + "  ").toCharArray();
		int cs, p = 0, pe = data.length, eof = pe, top = 0;
		int[] stack = new int[4];

		int s = 0;
		String name = null;
		String widgetLayoutString = null;
		String className = null;

		int columnDefaultCount = 0;
		ArrayList<String> values = new ArrayList(4);
		ArrayList<Object> parents = new ArrayList(8);
		Cell cell = null, rowDefaults = null, columnDefaults = null;
		Object parent = table, widget = null;
		RuntimeException parseRuntimeEx = null;
		boolean hasColon = false;

		boolean debug = false;
		if (debug) System.out.println();

		try {

			// line 3 "../src/com/esotericsoftware/tablelayout/TableLayoutParser.java"
			{
				cs = tableLayout_start;
				top = 0;
			}

			// line 8 "../src/com/esotericsoftware/tablelayout/TableLayoutParser.java"
			{
				int _klen;
				int _trans = 0;
				int _acts;
				int _nacts;
				int _keys;
				int _goto_targ = 0;

				_goto:
				while (true) {
					switch (_goto_targ) {
					case 0:
						if (p == pe) {
							_goto_targ = 4;
							continue _goto;
						}
						if (cs == 0) {
							_goto_targ = 5;
							continue _goto;
						}
					case 1:
						_match:
						do {
							_keys = _tableLayout_key_offsets[cs];
							_trans = _tableLayout_index_offsets[cs];
							_klen = _tableLayout_single_lengths[cs];
							if (_klen > 0) {
								int _lower = _keys;
								int _mid;
								int _upper = _keys + _klen - 1;
								while (true) {
									if (_upper < _lower) break;

									_mid = _lower + ((_upper - _lower) >> 1);
									if (data[p] < _tableLayout_trans_keys[_mid])
										_upper = _mid - 1;
									else if (data[p] > _tableLayout_trans_keys[_mid])
										_lower = _mid + 1;
									else {
										_trans += (_mid - _keys);
										break _match;
									}
								}
								_keys += _klen;
								_trans += _klen;
							}

							_klen = _tableLayout_range_lengths[cs];
							if (_klen > 0) {
								int _lower = _keys;
								int _mid;
								int _upper = _keys + (_klen << 1) - 2;
								while (true) {
									if (_upper < _lower) break;

									_mid = _lower + (((_upper - _lower) >> 1) & ~1);
									if (data[p] < _tableLayout_trans_keys[_mid])
										_upper = _mid - 2;
									else if (data[p] > _tableLayout_trans_keys[_mid + 1])
										_lower = _mid + 2;
									else {
										_trans += ((_mid - _keys) >> 1);
										break _match;
									}
								}
								_trans += _klen;
							}
						} while (false);

						cs = _tableLayout_trans_targs[_trans];

						if (_tableLayout_trans_actions[_trans] != 0) {
							_acts = _tableLayout_trans_actions[_trans];
							_nacts = (int)_tableLayout_actions[_acts++];
							while (_nacts-- > 0) {
								switch (_tableLayout_actions[_acts++]) {
								case 0:
									// line 41 "TableLayoutParser.rl"
								{
									s = p;
								}
									break;
								case 1:
									// line 42 "TableLayoutParser.rl"
								{
									name = new String(data, s, p - s);
									s = p;
								}
									break;
								case 2:
									// line 46 "TableLayoutParser.rl"
								{
									values.add(new String(data, s, p - s));
								}
									break;
								case 3:
									// line 49 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("tableProperty: " + name + " = " + values);
									((BaseTableLayout)parent).setTableProperty(name, values);
									values.clear();
									name = null;
								}
									break;
								case 4:
									// line 55 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("cellDefaultProperty: " + name + " = " + values);
									table.setCellProperty(((BaseTableLayout)parent).cellDefaults, name, values);
									values.clear();
									name = null;
								}
									break;
								case 5:
									// line 61 "TableLayoutParser.rl"
								{
									columnDefaults = ((BaseTableLayout)parent).getColumnDefaults(columnDefaultCount++);
								}
									break;
								case 6:
									// line 64 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("columnDefaultProperty: " + name + " = " + values);
									table.setCellProperty(columnDefaults, name, values);
									values.clear();
									name = null;
								}
									break;
								case 7:
									// line 70 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("startRow");
									rowDefaults = ((BaseTableLayout)parent).startRow();
								}
									break;
								case 8:
									// line 74 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("rowDefaultValue: " + name + " = " + values);
									table.setCellProperty(rowDefaults, name, values);
									values.clear();
									name = null;
								}
									break;
								case 9:
									// line 80 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("cellProperty: " + name + " = " + values);
									table.setCellProperty(cell, name, values);
									values.clear();
									name = null;
								}
									break;
								case 10:
									// line 86 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("widgetLayoutString: " + new String(data, s, p - s).trim());
									widgetLayoutString = new String(data, s, p - s).trim();
								}
									break;
								case 11:
									// line 90 "TableLayoutParser.rl"
								{
									className = new String(data, s, p - s);
								}
									break;
								case 12:
									// line 93 "TableLayoutParser.rl"
								{
									if (debug)
										System.out.println("newWidget, name:" + name + " class:" + className + " widget:" + widget);
									if (widget != null) { // 'label' or ['label'] or [name:'label']
										if (name != null && name.length() > 0) table.register(name, widget);
									} else if (className == null) {
										if (name.length() > 0) {
											if (hasColon) { // [name:]
												widget = table.wrap(null);
												table.register(name, widget);
											} else { // [name]
												widget = table.getWidget(name);
												if (widget == null) {
													// Try the widget name as a class name.
													try {
														widget = table.newWidget(name);
													} catch (RuntimeException ex) {
														throw new IllegalArgumentException("Widget not found with name: " + name);
													}
												}
											}
										} else
											// []
											widget = table.wrap(null);
									} else { // [:class] and [name:class]
										widget = table.newWidget(className);
										if (name.length() > 0) table.register(name, widget);
									}
									name = null;
									className = null;
								}
									break;
								case 13:
									// line 122 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("newLabel: " + new String(data, s, p - s));
									widget = table.wrap(new String(data, s, p - s));
								}
									break;
								case 14:
									// line 126 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("startTable, name:" + name);
									parents.add(parent);
									BaseTableLayout parentTable = null;
									for (int i = parents.size() - 1; i >= 0; i--) {
										Object object = parents.get(i);
										if (object instanceof BaseTableLayout) {
											parentTable = (BaseTableLayout)object;
											break;
										}
									}
									if (parentTable == null) parentTable = table;
									parent = parentTable.newTableLayout();
									if (name != null) { // [name:{}]
										table.register(name, ((BaseTableLayout)parent).getTable());
										name = null;
									}
									cell = null;
									widget = null;
									{
										if (top == stack.length) {
											int[] newStack = new int[stack.length * 2];
											System.arraycopy(stack, 0, newStack, 0, stack.length);
											stack = newStack;
										}
										{
											stack[top++] = cs;
											cs = 73;
											_goto_targ = 2;
											if (true) continue _goto;
										}
									}
								}
									break;
								case 15:
									// line 147 "TableLayoutParser.rl"
								{
									widget = parent;
									if (!parents.isEmpty()) {
										if (debug) System.out.println("endTable");
										parent = parents.remove(parents.size() - 1);
										{
											cs = stack[--top];
											_goto_targ = 2;
											if (true) continue _goto;
										}
									}
								}
									break;
								case 16:
									// line 155 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("startStack, name:" + name);
									parents.add(parent);
									parent = table.newStack();
									if (name != null) { // [name:<>]
										table.register(name, parent);
										name = null;
									}
									cell = null;
									widget = null;
									{
										if (top == stack.length) {
											int[] newStack = new int[stack.length * 2];
											System.arraycopy(stack, 0, newStack, 0, stack.length);
											stack = newStack;
										}
										{
											stack[top++] = cs;
											cs = 102;
											_goto_targ = 2;
											if (true) continue _goto;
										}
									}
								}
									break;
								case 17:
									// line 167 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("endStack");
									widget = parent;
									parent = parents.remove(parents.size() - 1);
									{
										cs = stack[--top];
										_goto_targ = 2;
										if (true) continue _goto;
									}
								}
									break;
								case 18:
									// line 173 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("startWidgetSection");
									parents.add(parent);
									parent = widget;
									widget = null;
									{
										if (top == stack.length) {
											int[] newStack = new int[stack.length * 2];
											System.arraycopy(stack, 0, newStack, 0, stack.length);
											stack = newStack;
										}
										{
											stack[top++] = cs;
											cs = 78;
											_goto_targ = 2;
											if (true) continue _goto;
										}
									}
								}
									break;
								case 19:
									// line 180 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("endWidgetSection");
									widget = parent;
									parent = parents.remove(parents.size() - 1);
									{
										cs = stack[--top];
										_goto_targ = 2;
										if (true) continue _goto;
									}
								}
									break;
								case 20:
									// line 186 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("addCell");
									cell = ((BaseTableLayout)parent).addCell(table.wrap(widget));
								}
									break;
								case 21:
									// line 190 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("addWidget");
									table.addChild(parent, table.wrap(widget), widgetLayoutString);
									widgetLayoutString = null;
								}
									break;
								case 22:
									// line 195 "TableLayoutParser.rl"
								{
									if (debug) System.out.println("widgetProperty: " + name + " = " + values);
									table.setProperty(parent, name, values);
									values.clear();
									name = null;
								}
									break;
								case 23:
									// line 212 "TableLayoutParser.rl"
								{
									widget = null;
									hasColon = false;
								}
									break;
								case 24:
									// line 213 "TableLayoutParser.rl"
								{
									hasColon = true;
								}
									break;
								// line 342 "../src/com/esotericsoftware/tablelayout/TableLayoutParser.java"
								}
							}
						}

					case 2:
						if (cs == 0) {
							_goto_targ = 5;
							continue _goto;
						}
						if (++p != pe) {
							_goto_targ = 1;
							continue _goto;
						}
					case 4:
					case 5:
					}
					break;
				}
			}

			// line 272 "TableLayoutParser.rl"

		} catch (RuntimeException ex) {
			parseRuntimeEx = ex;
		}

		if (p < pe) {
			int lineNumber = 1;
			for (int i = 0; i < p; i++)
				if (data[i] == '\n') lineNumber++;
			throw new IllegalArgumentException("Error parsing layout on line " + lineNumber + " near: "
				+ new String(data, p, pe - p), parseRuntimeEx);
		} else if (top > 0)
			throw new IllegalArgumentException("Error parsing layout (possibly an unmatched brace or quote): " + input,
				parseRuntimeEx);
	}

	// line 362 "../src/com/esotericsoftware/tablelayout/TableLayoutParser.java"
	private static byte[] init__tableLayout_actions_0 () {
		return new byte[] {0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9, 1, 11, 1, 12, 1, 13, 1, 14, 1, 15, 1, 16,
			1, 17, 1, 18, 1, 19, 1, 20, 1, 21, 1, 22, 1, 23, 2, 0, 2, 2, 0, 11, 2, 0, 13, 2, 1, 3, 2, 1, 4, 2, 1, 6, 2, 1, 8, 2, 1,
			9, 2, 1, 12, 2, 1, 22, 2, 1, 24, 2, 2, 3, 2, 2, 4, 2, 2, 6, 2, 2, 8, 2, 2, 9, 2, 2, 22, 2, 3, 14, 2, 3, 15, 2, 3, 16, 2,
			3, 23, 2, 4, 14, 2, 4, 15, 2, 4, 16, 2, 4, 23, 2, 5, 0, 2, 5, 14, 2, 5, 15, 2, 5, 16, 2, 5, 23, 2, 6, 14, 2, 6, 15, 2,
			6, 16, 2, 6, 23, 2, 7, 0, 2, 7, 14, 2, 7, 15, 2, 7, 16, 2, 7, 23, 2, 8, 14, 2, 8, 15, 2, 8, 16, 2, 8, 23, 2, 9, 14, 2,
			9, 15, 2, 9, 16, 2, 9, 18, 2, 9, 23, 2, 10, 21, 2, 11, 12, 2, 16, 0, 2, 20, 0, 2, 20, 14, 2, 20, 15, 2, 20, 16, 2, 20,
			18, 2, 20, 23, 2, 21, 14, 2, 21, 16, 2, 21, 17, 2, 21, 18, 2, 21, 19, 2, 21, 23, 2, 22, 14, 2, 22, 16, 2, 22, 19, 2, 22,
			23, 3, 0, 1, 12, 3, 0, 1, 24, 3, 1, 3, 14, 3, 1, 3, 15, 3, 1, 3, 16, 3, 1, 3, 23, 3, 1, 4, 14, 3, 1, 4, 15, 3, 1, 4, 16,
			3, 1, 4, 23, 3, 1, 6, 14, 3, 1, 6, 15, 3, 1, 6, 16, 3, 1, 6, 23, 3, 1, 8, 14, 3, 1, 8, 15, 3, 1, 8, 16, 3, 1, 8, 23, 3,
			1, 9, 14, 3, 1, 9, 15, 3, 1, 9, 16, 3, 1, 9, 18, 3, 1, 9, 23, 3, 1, 22, 14, 3, 1, 22, 16, 3, 1, 22, 19, 3, 1, 22, 23, 3,
			2, 3, 14, 3, 2, 3, 15, 3, 2, 3, 16, 3, 2, 3, 23, 3, 2, 4, 14, 3, 2, 4, 15, 3, 2, 4, 16, 3, 2, 4, 23, 3, 2, 6, 14, 3, 2,
			6, 15, 3, 2, 6, 16, 3, 2, 6, 23, 3, 2, 8, 14, 3, 2, 8, 15, 3, 2, 8, 16, 3, 2, 8, 23, 3, 2, 9, 14, 3, 2, 9, 15, 3, 2, 9,
			16, 3, 2, 9, 18, 3, 2, 9, 23, 3, 2, 22, 14, 3, 2, 22, 16, 3, 2, 22, 19, 3, 2, 22, 23, 3, 10, 21, 14, 3, 10, 21, 16, 3,
			10, 21, 18, 3, 10, 21, 19, 3, 10, 21, 23};
	}

	private static final byte _tableLayout_actions[] = init__tableLayout_actions_0();

	private static short[] init__tableLayout_key_offsets_0 () {
		return new short[] {0, 0, 17, 18, 19, 35, 51, 60, 61, 62, 77, 92, 108, 123, 135, 136, 137, 147, 161, 166, 168, 176, 183,
			191, 192, 193, 197, 206, 225, 235, 254, 255, 270, 285, 302, 319, 331, 332, 333, 344, 353, 373, 384, 404, 413, 430, 447,
			459, 460, 461, 472, 488, 504, 520, 537, 554, 566, 567, 568, 579, 588, 608, 619, 639, 648, 668, 679, 699, 717, 735, 747,
			748, 749, 761, 778, 787, 808, 820, 841, 855, 856, 857, 872, 880, 885, 887, 895, 902, 910, 911, 912, 916, 931, 946, 961,
			973, 974, 975, 984, 993, 1012, 1021, 1039, 1047, 1048, 1049, 1058, 1067, 1072, 1074, 1082, 1089, 1097, 1098, 1099, 1103,
			1106, 1106};
	}

	private static final short _tableLayout_key_offsets[] = init__tableLayout_key_offsets_0();

	private static char[] init__tableLayout_trans_keys_0 () {
		return new char[] {32, 39, 42, 45, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32, 39, 40, 45, 60, 91,
			123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 40, 45, 60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45,
			60, 91, 123, 125, 9, 13, 45, 45, 32, 39, 45, 60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45, 60, 91, 123,
			125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45, 58, 60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 58, 60,
			91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 46, 95, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32, 39, 44, 45,
			60, 91, 123, 125, 9, 13, 32, 39, 60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 58, 93, 9, 13, 58, 93, 32, 39,
			58, 60, 93, 123, 9, 13, 32, 39, 58, 93, 123, 9, 13, 32, 39, 58, 60, 93, 123, 9, 13, 39, 39, 32, 93, 9, 13, 39, 46, 95,
			48, 57, 65, 90, 97, 122, 32, 37, 39, 44, 45, 46, 60, 91, 95, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 44, 45,
			60, 91, 123, 125, 9, 13, 32, 37, 39, 44, 45, 46, 60, 91, 95, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 45, 32, 39, 45,
			60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45, 60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39,
			40, 45, 58, 60, 91, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 40, 45, 58, 60, 91, 123, 125, 9, 13, 48, 57, 65,
			90, 97, 122, 32, 39, 46, 95, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32, 39, 40, 44, 45, 60, 91, 123, 125, 9, 13, 39,
			46, 95, 48, 57, 65, 90, 97, 122, 32, 37, 39, 40, 44, 45, 46, 60, 91, 95, 123, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32,
			39, 40, 44, 45, 60, 91, 123, 125, 9, 13, 32, 37, 39, 40, 44, 45, 46, 60, 91, 95, 123, 125, 9, 13, 48, 57, 65, 90, 97,
			122, 32, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45, 58, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39,
			45, 58, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 46, 95, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39,
			32, 39, 44, 45, 60, 91, 123, 124, 125, 9, 13, 32, 39, 45, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39,
			45, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97,
			122, 32, 39, 45, 58, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 45, 58, 60, 91, 123, 124, 125, 9,
			13, 48, 57, 65, 90, 97, 122, 32, 39, 46, 95, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32, 39, 44, 45, 60, 91, 123, 124,
			125, 9, 13, 39, 46, 95, 48, 57, 65, 90, 97, 122, 32, 37, 39, 44, 45, 46, 60, 91, 95, 123, 124, 125, 9, 13, 48, 57, 65,
			90, 97, 122, 32, 39, 44, 45, 60, 91, 123, 124, 125, 9, 13, 32, 37, 39, 44, 45, 46, 60, 91, 95, 123, 124, 125, 9, 13, 48,
			57, 65, 90, 97, 122, 39, 46, 95, 48, 57, 65, 90, 97, 122, 32, 37, 39, 44, 45, 46, 60, 91, 95, 123, 124, 125, 9, 13, 48,
			57, 65, 90, 97, 122, 32, 39, 44, 45, 60, 91, 123, 124, 125, 9, 13, 32, 37, 39, 44, 45, 46, 60, 91, 95, 123, 124, 125, 9,
			13, 48, 57, 65, 90, 97, 122, 32, 39, 42, 45, 58, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 42, 45,
			58, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 46, 95, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32,
			39, 42, 44, 45, 60, 91, 123, 124, 125, 9, 13, 32, 39, 42, 45, 60, 91, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122, 39,
			46, 95, 48, 57, 65, 90, 97, 122, 32, 37, 39, 42, 44, 45, 46, 60, 91, 95, 123, 124, 125, 9, 13, 48, 57, 65, 90, 97, 122,
			32, 39, 42, 44, 45, 60, 91, 123, 124, 125, 9, 13, 32, 37, 39, 42, 44, 45, 46, 60, 91, 95, 123, 124, 125, 9, 13, 48, 57,
			65, 90, 97, 122, 32, 39, 41, 60, 91, 123, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32, 39, 40, 41, 60, 91, 123, 9, 13,
			48, 57, 65, 90, 97, 122, 32, 39, 41, 60, 91, 123, 9, 13, 32, 58, 93, 9, 13, 58, 93, 32, 39, 58, 60, 93, 123, 9, 13, 32,
			39, 58, 93, 123, 9, 13, 32, 39, 58, 60, 93, 123, 9, 13, 39, 39, 32, 93, 9, 13, 32, 39, 40, 41, 60, 91, 123, 9, 13, 48,
			57, 65, 90, 97, 122, 32, 39, 41, 58, 60, 91, 123, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 41, 58, 60, 91, 123, 9, 13,
			48, 57, 65, 90, 97, 122, 32, 39, 46, 95, 9, 13, 48, 57, 65, 90, 97, 122, 39, 39, 32, 39, 41, 44, 60, 91, 123, 9, 13, 39,
			46, 95, 48, 57, 65, 90, 97, 122, 32, 37, 39, 41, 44, 45, 46, 60, 91, 95, 123, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39,
			41, 44, 60, 91, 123, 9, 13, 32, 37, 39, 41, 44, 46, 60, 91, 95, 123, 9, 13, 48, 57, 65, 90, 97, 122, 32, 39, 60, 62, 91,
			123, 9, 13, 39, 39, 32, 39, 40, 60, 62, 91, 123, 9, 13, 32, 39, 40, 60, 62, 91, 123, 9, 13, 32, 58, 93, 9, 13, 58, 93,
			32, 39, 58, 60, 93, 123, 9, 13, 32, 39, 58, 93, 123, 9, 13, 32, 39, 58, 60, 93, 123, 9, 13, 39, 39, 32, 93, 9, 13, 32,
			9, 13, 0};
	}

	private static final char _tableLayout_trans_keys[] = init__tableLayout_trans_keys_0();

	private static byte[] init__tableLayout_single_lengths_0 () {
		return new byte[] {0, 9, 1, 1, 8, 8, 7, 1, 1, 7, 7, 8, 7, 4, 1, 1, 8, 6, 3, 2, 6, 5, 6, 1, 1, 2, 3, 11, 8, 11, 1, 7, 7, 9,
			9, 4, 1, 1, 9, 3, 12, 9, 12, 1, 9, 9, 4, 1, 1, 9, 8, 8, 8, 9, 9, 4, 1, 1, 9, 3, 12, 9, 12, 3, 12, 9, 12, 10, 10, 4, 1,
			1, 10, 9, 3, 13, 10, 13, 6, 1, 1, 7, 6, 3, 2, 6, 5, 6, 1, 1, 2, 7, 7, 7, 4, 1, 1, 7, 3, 11, 7, 10, 6, 1, 1, 7, 7, 3, 2,
			6, 5, 6, 1, 1, 2, 1, 0, 0};
	}

	private static final byte _tableLayout_single_lengths[] = init__tableLayout_single_lengths_0();

	private static byte[] init__tableLayout_range_lengths_0 () {
		return new byte[] {0, 4, 0, 0, 4, 4, 1, 0, 0, 4, 4, 4, 4, 4, 0, 0, 1, 4, 1, 0, 1, 1, 1, 0, 0, 1, 3, 4, 1, 4, 0, 4, 4, 4, 4,
			4, 0, 0, 1, 3, 4, 1, 4, 4, 4, 4, 4, 0, 0, 1, 4, 4, 4, 4, 4, 4, 0, 0, 1, 3, 4, 1, 4, 3, 4, 1, 4, 4, 4, 4, 0, 0, 1, 4, 3,
			4, 1, 4, 4, 0, 0, 4, 1, 1, 0, 1, 1, 1, 0, 0, 1, 4, 4, 4, 4, 0, 0, 1, 3, 4, 1, 4, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
			1, 0, 0};
	}

	private static final byte _tableLayout_range_lengths[] = init__tableLayout_range_lengths_0();

	private static short[] init__tableLayout_index_offsets_0 () {
		return new short[] {0, 0, 14, 16, 18, 31, 44, 53, 55, 57, 69, 81, 94, 106, 115, 117, 119, 129, 140, 145, 148, 156, 163,
			171, 173, 175, 179, 186, 202, 212, 228, 230, 242, 254, 268, 282, 291, 293, 295, 306, 313, 330, 341, 358, 364, 378, 392,
			401, 403, 405, 416, 429, 442, 455, 469, 483, 492, 494, 496, 507, 514, 531, 542, 559, 566, 583, 594, 611, 626, 641, 650,
			652, 654, 666, 680, 687, 705, 717, 735, 746, 748, 750, 762, 770, 775, 778, 786, 793, 801, 803, 805, 809, 821, 833, 845,
			854, 856, 858, 867, 874, 890, 899, 914, 922, 924, 926, 935, 944, 949, 952, 960, 967, 975, 977, 979, 983, 986, 987};
	}

	private static final short _tableLayout_index_offsets[] = init__tableLayout_index_offsets_0();

	private static byte[] init__tableLayout_trans_targs_0 () {
		return new byte[] {1, 2, 43, 7, 4, 18, 73, 51, 115, 1, 67, 67, 67, 0, 4, 3, 4, 3, 5, 2, 6, 7, 4, 18, 4, 115, 5, 33, 33, 33,
			0, 5, 2, 6, 7, 4, 18, 4, 115, 5, 33, 33, 33, 0, 6, 2, 7, 4, 18, 4, 115, 6, 0, 8, 0, 9, 0, 10, 2, 7, 4, 18, 4, 115, 10,
			11, 11, 11, 0, 10, 2, 7, 4, 18, 4, 115, 10, 11, 11, 11, 0, 12, 2, 7, 13, 4, 18, 4, 115, 12, 11, 11, 11, 0, 12, 2, 13, 4,
			18, 4, 115, 12, 11, 11, 11, 0, 13, 14, 27, 27, 13, 27, 27, 27, 0, 16, 15, 16, 15, 17, 2, 26, 7, 4, 18, 4, 115, 17, 0,
			17, 2, 4, 18, 4, 115, 17, 11, 11, 11, 0, 18, 20, 4, 18, 19, 20, 4, 19, 22, 23, 0, 21, 4, 25, 22, 21, 21, 0, 0, 4, 0, 21,
			21, 22, 23, 0, 21, 4, 25, 22, 21, 25, 24, 25, 24, 25, 4, 25, 0, 14, 27, 27, 27, 27, 27, 0, 17, 28, 2, 26, 29, 27, 4, 18,
			27, 4, 115, 17, 27, 27, 27, 0, 17, 2, 26, 7, 4, 18, 4, 115, 17, 0, 17, 28, 2, 26, 30, 27, 4, 18, 27, 4, 115, 17, 27, 27,
			27, 0, 31, 0, 10, 2, 32, 4, 18, 4, 115, 10, 11, 11, 11, 0, 10, 2, 30, 4, 18, 4, 115, 10, 11, 11, 11, 0, 34, 2, 6, 7, 35,
			4, 18, 4, 115, 34, 33, 33, 33, 0, 34, 2, 6, 7, 35, 4, 18, 4, 115, 34, 33, 33, 33, 0, 35, 36, 40, 40, 35, 40, 40, 40, 0,
			38, 37, 38, 37, 5, 2, 6, 39, 7, 4, 18, 4, 115, 5, 0, 36, 40, 40, 40, 40, 40, 0, 5, 41, 2, 6, 39, 42, 40, 4, 18, 40, 4,
			115, 5, 40, 40, 40, 0, 5, 2, 6, 39, 7, 4, 18, 4, 115, 5, 0, 5, 41, 2, 6, 39, 30, 40, 4, 18, 40, 4, 115, 5, 40, 40, 40,
			0, 43, 43, 44, 44, 44, 0, 45, 2, 7, 46, 4, 18, 4, 51, 115, 45, 44, 44, 44, 0, 45, 2, 7, 46, 4, 18, 4, 51, 115, 45, 44,
			44, 44, 0, 46, 47, 64, 64, 46, 64, 64, 64, 0, 49, 48, 49, 48, 50, 2, 63, 7, 4, 18, 4, 51, 115, 50, 0, 50, 2, 7, 4, 18,
			4, 51, 115, 50, 44, 44, 44, 0, 52, 2, 7, 4, 18, 4, 51, 115, 52, 53, 53, 53, 0, 52, 2, 7, 4, 18, 4, 51, 115, 52, 53, 53,
			53, 0, 54, 2, 7, 55, 4, 18, 4, 51, 115, 54, 53, 53, 53, 0, 54, 2, 7, 55, 4, 18, 4, 51, 115, 54, 53, 53, 53, 0, 55, 56,
			60, 60, 55, 60, 60, 60, 0, 58, 57, 58, 57, 52, 2, 59, 7, 4, 18, 4, 51, 115, 52, 0, 56, 60, 60, 60, 60, 60, 0, 52, 61, 2,
			59, 62, 60, 4, 18, 60, 4, 51, 115, 52, 60, 60, 60, 0, 52, 2, 59, 7, 4, 18, 4, 51, 115, 52, 0, 52, 61, 2, 59, 30, 60, 4,
			18, 60, 4, 51, 115, 52, 60, 60, 60, 0, 47, 64, 64, 64, 64, 64, 0, 50, 65, 2, 63, 66, 64, 4, 18, 64, 4, 51, 115, 50, 64,
			64, 64, 0, 50, 2, 63, 7, 4, 18, 4, 51, 115, 50, 0, 50, 65, 2, 63, 30, 64, 4, 18, 64, 4, 51, 115, 50, 64, 64, 64, 0, 68,
			2, 43, 7, 69, 4, 18, 4, 51, 115, 68, 67, 67, 67, 0, 68, 2, 43, 7, 69, 4, 18, 4, 51, 115, 68, 67, 67, 67, 0, 69, 70, 75,
			75, 69, 75, 75, 75, 0, 72, 71, 72, 71, 73, 2, 43, 74, 7, 4, 18, 4, 51, 115, 73, 0, 73, 2, 43, 7, 4, 18, 4, 51, 115, 73,
			67, 67, 67, 0, 70, 75, 75, 75, 75, 75, 0, 73, 76, 2, 43, 74, 77, 75, 4, 18, 75, 4, 51, 115, 73, 75, 75, 75, 0, 73, 2,
			43, 74, 7, 4, 18, 4, 51, 115, 73, 0, 73, 76, 2, 43, 74, 30, 75, 4, 18, 75, 4, 51, 115, 73, 75, 75, 75, 0, 78, 79, 116,
			81, 83, 81, 78, 92, 92, 92, 0, 81, 80, 81, 80, 81, 79, 82, 116, 81, 83, 81, 81, 91, 91, 91, 0, 82, 79, 116, 81, 83, 81,
			82, 0, 83, 85, 81, 83, 84, 85, 81, 84, 87, 88, 0, 86, 81, 90, 87, 86, 86, 0, 0, 81, 0, 86, 86, 87, 88, 0, 86, 81, 90,
			87, 86, 90, 89, 90, 89, 90, 81, 90, 0, 91, 79, 82, 116, 81, 83, 81, 82, 91, 91, 91, 0, 93, 79, 116, 94, 81, 83, 81, 93,
			92, 92, 92, 0, 93, 79, 116, 94, 81, 83, 81, 93, 92, 92, 92, 0, 94, 95, 99, 99, 94, 99, 99, 99, 0, 97, 96, 97, 96, 78,
			79, 116, 98, 81, 83, 81, 78, 0, 95, 99, 99, 99, 99, 99, 0, 78, 100, 79, 116, 98, 101, 99, 81, 83, 99, 81, 78, 99, 99,
			99, 0, 78, 79, 116, 98, 81, 83, 81, 78, 0, 78, 100, 79, 116, 98, 99, 81, 83, 99, 81, 78, 99, 99, 99, 0, 102, 103, 105,
			117, 107, 105, 102, 0, 105, 104, 105, 104, 106, 103, 102, 105, 117, 107, 105, 106, 0, 106, 103, 102, 105, 117, 107, 105,
			106, 0, 107, 109, 105, 107, 108, 109, 105, 108, 111, 112, 0, 110, 105, 114, 111, 110, 110, 0, 0, 105, 0, 110, 110, 111,
			112, 0, 110, 105, 114, 111, 110, 114, 113, 114, 113, 114, 105, 114, 0, 115, 115, 0, 0, 0, 0};
	}

	private static final byte _tableLayout_trans_targs[] = init__tableLayout_trans_targs_0();

	private static short[] init__tableLayout_trans_actions_0 () {
		return new short[] {0, 0, 0, 0, 31, 45, 0, 0, 29, 0, 1, 1, 1, 0, 53, 1, 25, 0, 39, 39, 212, 39, 209, 215, 203, 206, 39,
			200, 200, 200, 0, 0, 0, 35, 0, 31, 45, 27, 29, 0, 1, 1, 1, 0, 0, 0, 0, 31, 45, 27, 29, 0, 0, 0, 0, 0, 0, 15, 15, 15,
			158, 161, 152, 155, 15, 149, 149, 149, 0, 0, 0, 0, 31, 45, 27, 29, 0, 1, 1, 1, 0, 65, 65, 65, 3, 312, 316, 304, 308, 65,
			0, 0, 0, 0, 0, 0, 0, 31, 45, 27, 29, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 47, 1, 5, 0, 17, 17, 0, 17, 170, 173,
			164, 167, 17, 0, 0, 0, 31, 45, 27, 29, 0, 1, 1, 1, 0, 1, 252, 248, 1, 1, 77, 71, 0, 1, 0, 0, 197, 23, 27, 1, 1, 21, 0,
			0, 194, 0, 21, 0, 50, 0, 0, 197, 194, 27, 50, 1, 53, 1, 25, 0, 0, 23, 0, 0, 0, 1, 1, 1, 1, 1, 0, 89, 0, 89, 5, 89, 0,
			412, 416, 0, 404, 408, 89, 0, 0, 0, 0, 89, 89, 5, 89, 412, 416, 404, 408, 89, 0, 89, 0, 89, 5, 89, 0, 412, 416, 0, 404,
			408, 89, 0, 0, 0, 0, 0, 0, 15, 15, 15, 158, 161, 152, 155, 15, 149, 149, 149, 0, 15, 15, 15, 158, 161, 152, 155, 15,
			149, 149, 149, 0, 68, 68, 332, 68, 3, 328, 336, 320, 324, 68, 0, 0, 0, 0, 0, 0, 35, 0, 0, 31, 45, 27, 29, 0, 1, 1, 1, 0,
			0, 0, 1, 1, 0, 1, 1, 1, 0, 47, 1, 5, 0, 19, 19, 185, 0, 19, 182, 188, 176, 179, 19, 0, 0, 1, 1, 1, 1, 1, 0, 92, 0, 92,
			432, 5, 92, 0, 428, 436, 0, 420, 424, 92, 0, 0, 0, 0, 92, 92, 432, 5, 92, 428, 436, 420, 424, 92, 0, 92, 0, 92, 432, 5,
			92, 0, 428, 436, 0, 420, 424, 92, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 59, 59, 59, 3, 280, 284, 272, 59, 276, 59, 0, 0, 0, 0,
			0, 0, 0, 0, 31, 45, 27, 0, 29, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 47, 1, 5, 0, 9, 9, 0, 9, 116, 119, 110, 9, 113,
			9, 0, 0, 0, 0, 31, 45, 27, 0, 29, 0, 1, 1, 1, 0, 11, 11, 11, 131, 134, 125, 11, 128, 11, 122, 122, 122, 0, 0, 0, 0, 31,
			45, 27, 0, 29, 0, 1, 1, 1, 0, 62, 62, 62, 3, 296, 300, 288, 62, 292, 62, 0, 0, 0, 0, 0, 0, 0, 0, 31, 45, 27, 0, 29, 0,
			1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 47, 1, 5, 0, 13, 13, 0, 13, 143, 146, 137, 13, 140, 13, 0, 0, 1, 1, 1, 1, 1, 0,
			86, 0, 86, 5, 86, 0, 396, 400, 0, 388, 86, 392, 86, 0, 0, 0, 0, 86, 86, 5, 86, 396, 400, 388, 86, 392, 86, 0, 86, 0, 86,
			5, 86, 0, 396, 400, 0, 388, 86, 392, 86, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 83, 0, 83, 5, 83, 0, 380, 384, 0, 372, 83,
			376, 83, 0, 0, 0, 0, 83, 83, 5, 83, 380, 384, 372, 83, 376, 83, 0, 83, 0, 83, 5, 83, 0, 380, 384, 0, 372, 83, 376, 83,
			0, 0, 0, 0, 56, 56, 56, 56, 3, 264, 268, 256, 56, 260, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 45, 27, 0, 29, 0, 1, 1, 1, 0,
			0, 0, 1, 1, 0, 1, 1, 1, 0, 47, 1, 5, 0, 7, 7, 7, 0, 7, 104, 107, 98, 7, 101, 7, 0, 0, 0, 0, 0, 31, 45, 27, 0, 29, 0, 1,
			1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 80, 0, 80, 80, 5, 80, 0, 364, 368, 0, 356, 80, 360, 80, 0, 0, 0, 0, 80, 80, 80, 5, 80,
			364, 368, 356, 80, 360, 80, 0, 80, 0, 80, 80, 5, 80, 0, 364, 368, 0, 356, 80, 360, 80, 0, 0, 0, 0, 0, 0, 37, 31, 45, 27,
			0, 1, 1, 1, 0, 53, 1, 25, 0, 0, 41, 227, 230, 221, 233, 218, 0, 1, 1, 1, 0, 0, 0, 37, 31, 45, 27, 0, 0, 1, 252, 248, 1,
			1, 77, 71, 0, 1, 0, 0, 197, 23, 27, 1, 1, 21, 0, 0, 194, 0, 21, 0, 50, 0, 0, 197, 194, 27, 50, 1, 53, 1, 25, 0, 0, 23,
			0, 0, 0, 191, 464, 468, 460, 472, 456, 191, 0, 0, 0, 0, 74, 74, 348, 3, 344, 352, 340, 74, 0, 0, 0, 0, 0, 0, 37, 0, 31,
			45, 27, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 47, 1, 5, 0, 43, 43, 242, 0, 239, 245, 236, 43, 0, 0, 1, 1, 1, 1, 1,
			0, 95, 0, 95, 448, 5, 0, 0, 444, 452, 0, 440, 95, 0, 0, 0, 0, 95, 95, 448, 5, 444, 452, 440, 95, 0, 95, 0, 95, 448, 5,
			0, 444, 452, 0, 440, 95, 0, 0, 0, 0, 0, 0, 31, 33, 45, 27, 0, 0, 53, 1, 25, 0, 41, 41, 227, 221, 224, 233, 218, 41, 0,
			0, 0, 35, 31, 33, 45, 27, 0, 0, 1, 252, 248, 1, 1, 77, 71, 0, 1, 0, 0, 197, 23, 27, 1, 1, 21, 0, 0, 194, 0, 21, 0, 50,
			0, 0, 197, 194, 27, 50, 1, 53, 1, 25, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0};
	}

	private static final short _tableLayout_trans_actions[] = init__tableLayout_trans_actions_0();

	static final int tableLayout_start = 1;
	static final int tableLayout_first_final = 115;
	static final int tableLayout_error = 0;

	static final int tableLayout_en_widgetSection = 78;
	static final int tableLayout_en_stack = 102;
	static final int tableLayout_en_main = 1;
	static final int tableLayout_en_main_table = 73;

	// line 287 "TableLayoutParser.rl"
}
